services:
  postgres: 
    image: postgres:17
    container_name: webhooks
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: webhooks_db
    ports:
      - '5432:5432'